### ISSUE TITLE
Estilização da página de perfil 

### ISSUE THREAD

**Issue by MatheusInte** [upe-garanhuns/pweb-2023.2-react#15]
#### Descrição

Irei estilizar o componente responsável por mostrar o perfil do usuário na página.

#### Arquivos

Arquivo Profile.css, Profile.jsx

#### Tasks 

- [x] Refatoração do nome dos arquivos colocados erroneamente
- [x] Adição das className necessárias
- [x] Estilização do componente
