### ISSUE TITLE
Persitência dos dados

### ISSUE THREAD

**Issue by Guiioff** [upe-garanhuns/pweb-2023.2-react#6]
**Descrição**
Permita que quando o formulário de cadastro seja enviado, os dados sejam salvos

**Arquivos**
Adicione o json-server no package.json e crie data/db.json para guardar as informações das pessoas

**Tasks**

- [x] Instalação da biblioteca json-server
- [x] Criação do hook responsável pelas requisições http
- [x] Métodos responsáveis pela persistência dos dados da pessoa
